# Generated by Django 3.1.4 on 2021-01-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnalookupapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
